

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2017 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-3FBD-7F04-2C                      |
; |                      Jiang Ying, Personal license                       |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 255C479487426356912C4DFA027A7D683BF0A9878CB41C55E274390DE22FA915
; Input MD5    : 490CC687207DA2BB438E6A5203437F66
; Input CRC32  : 9DE65FA4

; File Name   : E:\h3e\1\h8dev_02\h8led.bin.000.origin.242.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 00F2h Loaded length: 00F2h

; Processor       : h8300a
; Target assembler: GNU assembler
; Byte sex        : Big endian

                .h8300h

; ===========================================================================

; Segment type: Pure code
                .text; ROM
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x5E ; ^
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
; ---------------------------------------------------------------------------
                mov.l   #0xFF80, sp
                mov.l   #0xF2, er0
                mov.l   #0xF2, er1
                mov.l   #0xF2, er2

loc_4C:                                 ; CODE XREF: ROM:00000056↓j
                mov.w   @er0, r3
                mov.w   r3, @er1
                adds    #2, er0
                adds    #2, er1
                cmp.l   er2, er1
                bcs     loc_4C:8

loc_58:                                 ; CODE XREF: ROM:0000005C↓j
                jsr     sub_B2:24
                bra     loc_58:8
; ---------------------------------------------------------------------------
                push.l  er6
                mov.l   sp, er6
                push.l  er0
                push.l  er1
                push.l  er2
                push.l  er3
                push.l  er4
                push.l  er5
                mov.l   #0xFFF6, er3
                mov.b   @er3, r2l
                and.b   #0x9F, r2l
                mov.b   r2l, @er3
                mov.l   #0xFFD4, er3
                mov.b   @er3, r2l
                not.b   r2l
                mov.b   r2l, @er3
                pop.l   er5
                pop.l   er4
                pop.l   er3
                pop.l   er2
                pop.l   er1
                pop.l   er0
                pop.l   er6
                rte

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_B2:                                 ; CODE XREF: ROM:loc_58↑p
                push.l  er6
                mov.l   sp, er6
                mov.l   #0xFFE0, er2
                sub.b   r0l, r0l
                mov.b   r0l, @er2
                mov.l   #0xFFE4, er3
                mov.b   #0xFF, r2l
                mov.b   r2l, @er3
                mov.l   #0xFFD4, er2
                mov.b   r0l, @er2
                mov.l   #0xFFA6, er3
                mov.b   #0x99, r2l
                mov.b   r2l, @er3
                mov.l   #0xFFF4, er3
                mov.b   @er3, r2l
                or.b    #0x40, r2l
                mov.b   r2l, @er3
                andc    #0x7F, ccr

loc_EC:                                 ; CODE XREF: sub_B2+3C↓j
                sleep
                bra     loc_EC:16
; End of function sub_B2


                ; end
