

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2017 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-3FBD-7F04-2C                      |
; |                      Jiang Ying, Personal license                       |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 6EED316257BE3C398B7ACE878D9D6ADE95CACD3BC13D8394034F24710BE7C06E
; Input MD5    : F7BCBB2B8FB9F28578EC7876612C751C
; Input CRC32  : F16F94CC

; File Name   : E:\h3e\1\h8dev_02\h8led.bin.002.194.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 00C2h Loaded length: 00C2h

; Processor       : h8300a
; Target assembler: GNU assembler
; Byte sex        : Big endian

                .h8300h

; ===========================================================================

; Segment type: Pure code
                .text; ROM
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x5E ; ^
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
                .byte    0
                .byte 0x34 ; 4
; ---------------------------------------------------------------------------
                mov.l   #0x5E, sp ; '^'
                mov.l   #0xC2, er0
                mov.l   #0xC2, er1
                mov.l   #0xC2, er2

loc_4C:                                 ; CODE XREF: ROM:00000056↓j
                mov.w   @er0, r3
                mov.w   r3, @er1
                adds    #2, er0
                adds    #2, er1
                cmp.l   er2, er1
                bcs     loc_4C:8

loc_58:                                 ; CODE XREF: ROM:0000005C↓j
                jsr     sub_8E:24
                bra     loc_58:8
; ---------------------------------------------------------------------------
                push.l  er6
                mov.l   sp, er6
                push.l  er2
                push.l  er3
                mov.l   #0xFFF6, er2
                mov.b   @er2, r3l
                and.b   #0x9F, r3l
                mov.b   r3l, @er2
                mov.b   #0xD4, r2l
                mov.b   @er2, r3l
                not.b   r3l
                mov.b   r3l, @er2
                pop.l   er3
                pop.l   er2
                pop.l   er6
                rte

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_8E:                                 ; CODE XREF: ROM:loc_58↑p
                push.l  er6
                mov.l   sp, er6
                sub.b   r2l, r2l
                mov.b   r2l, @0xFFE0:32
                mov.b   #0xFF, r3l
                mov.b   r3l, @PCR1:32
                mov.b   r2l, @PDR1:32
                mov.b   #0x99, r2l
                mov.b   r2l, @0xFFA6:32
                mov.l   #0xFFF4, er2
                bset    #6, @er2
                andc    #0x7F, ccr

loc_BE:                                 ; CODE XREF: sub_8E+32↓j
                sleep
                bra     loc_BE:8
; End of function sub_8E


                ; end
